/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.uv.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author asunawesker
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        mnCourseCreate = new javax.swing.JMenu();
        jMenuCourse = new javax.swing.JMenuItem();
        mnProfessorCreate = new javax.swing.JMenuItem();
        mnStudentCreate = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnCourseSearch = new javax.swing.JMenuItem();
        mnProfessorSearch = new javax.swing.JMenuItem();
        mnStudentSearch = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnCourseUpdate = new javax.swing.JMenuItem();
        mnProfessorUpdate = new javax.swing.JMenuItem();
        mnStudentUpdate = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(612, 450));

        jDesktopPane1.setToolTipText("");
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(700, 500));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(700, 500));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 700));
        jDesktopPane1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Inicio");

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        mnCourseCreate.setText("Agregar");

        jMenuCourse.setText("Curso");
        jMenuCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCourseActionPerformed(evt);
            }
        });
        mnCourseCreate.add(jMenuCourse);

        mnProfessorCreate.setText("Profesor");
        mnProfessorCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProfessorCreateActionPerformed(evt);
            }
        });
        mnCourseCreate.add(mnProfessorCreate);

        mnStudentCreate.setText("Estudiante");
        mnStudentCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudentCreateActionPerformed(evt);
            }
        });
        mnCourseCreate.add(mnStudentCreate);

        jMenuBar1.add(mnCourseCreate);

        jMenu3.setText("Buscar");

        mnCourseSearch.setText("Curso");
        mnCourseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCourseSearchActionPerformed(evt);
            }
        });
        jMenu3.add(mnCourseSearch);

        mnProfessorSearch.setText("Profesor");
        mnProfessorSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProfessorSearchActionPerformed(evt);
            }
        });
        jMenu3.add(mnProfessorSearch);

        mnStudentSearch.setText("Estudiante");
        mnStudentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudentSearchActionPerformed(evt);
            }
        });
        jMenu3.add(mnStudentSearch);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Actualizar");

        mnCourseUpdate.setText("Curso");
        mnCourseUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCourseUpdateActionPerformed(evt);
            }
        });
        jMenu4.add(mnCourseUpdate);

        mnProfessorUpdate.setText("Profesor");
        mnProfessorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProfessorUpdateActionPerformed(evt);
            }
        });
        jMenu4.add(mnProfessorUpdate);

        mnStudentUpdate.setText("Estudiante");
        mnStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudentUpdateActionPerformed(evt);
            }
        });
        jMenu4.add(mnStudentUpdate);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCourseActionPerformed
        // TODO add your handling code here:
        CourseCreate course; 
        try {          
            course = new CourseCreate();
            jDesktopPane1.add(course);
            course.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuCourseActionPerformed

    private void mnStudentCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudentCreateActionPerformed
        // TODO add your handling code here:
        StudentCreate student;
        
        try {
            student = new StudentCreate();
             jDesktopPane1.add(student);
             student.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_mnStudentCreateActionPerformed

    private void jMenuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfessorActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jMenuProfessorActionPerformed

    private void mnCourseUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCourseUpdateActionPerformed
        // TODO add your handling code here:
        CourseUpdate course;
        
        try {
            course = new CourseUpdate();
            jDesktopPane1.add(course);
            course.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCourseUpdateActionPerformed

    private void mnStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudentUpdateActionPerformed
        // TODO add your handling code here:
        StudentUpdate student;
        
        try {
            student = new StudentUpdate();
            jDesktopPane1.add(student);
            student.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnStudentUpdateActionPerformed

    private void mnCourseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCourseSearchActionPerformed
        // TODO add your handling code here:
        CourseSearch course;
        
        try {
            course = new CourseSearch();
            jDesktopPane1.add(course);
            course.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCourseSearchActionPerformed

    private void mnProfessorSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProfessorSearchActionPerformed
        // TODO add your handling code here:
        ProfessorSearch professor;
        
        try {
            professor = new ProfessorSearch();
            jDesktopPane1.add(professor);
            professor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnProfessorSearchActionPerformed

    private void mnStudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudentSearchActionPerformed
        // TODO add your handling code here:
        StudentSearch student;
        
        try {
            student = new StudentSearch();
             jDesktopPane1.add(student);
            student.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_mnStudentSearchActionPerformed

    private void mnProfessorCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProfessorCreateActionPerformed
        // TODO add your handling code here:
        ProfessorCreate professor;
        
        try {
            professor = new ProfessorCreate();
            jDesktopPane1.add(professor);
            professor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_mnProfessorCreateActionPerformed

    private void mnProfessorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProfessorUpdateActionPerformed
        // TODO add your handling code here:
        ProfessorUpdate professor;
        
        try {
            professor = new ProfessorUpdate();
            jDesktopPane1.add(professor);
            professor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnProfessorUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCourse;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnCourseCreate;
    private javax.swing.JMenuItem mnCourseSearch;
    private javax.swing.JMenuItem mnCourseUpdate;
    private javax.swing.JMenuItem mnProfessorCreate;
    private javax.swing.JMenuItem mnProfessorSearch;
    private javax.swing.JMenuItem mnProfessorUpdate;
    private javax.swing.JMenuItem mnStudentCreate;
    private javax.swing.JMenuItem mnStudentSearch;
    private javax.swing.JMenuItem mnStudentUpdate;
    // End of variables declaration//GEN-END:variables
}
